name: CXARM CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - 'README.md'
    - '.devcontainer/**'
    - '.vscode/**'

env:
  IAR_LMS_BEARER_TOKEN: ${{ secrets.IAR_LMS_BEARER_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/arm:9.60.4-st
    steps:
    - name: Invoke the IAR C/C++ Compiler for Arm
      run: iccarm --version
    - name: Checkout project
      uses: actions/checkout@v4
    - name: CMake - Configure
      run: cmake --preset cxarm-linux
    - name: CMake - Build
      run: cmake --build build --config Debug --verbose

  verify:
    name: Verify
    needs: build
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/arm:9.60.4-st
    timeout-minutes: 5
    steps:      
    - name: Checkout project
      uses: actions/checkout@v4
    - name: IAR C-STAT, Static Analysis
      run: iarbuild light-effects-cmake.ewp -cstat_analyze Debug -log all -parallel 4

  deploy:
    name: Deploy
    needs: verify
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/iarsystems/arm:9.60.4-st
    steps:      
    - name: Checkout project
      uses: actions/checkout@v4
    - name: CMake - Configure
      run: cmake --preset cxarm-linux
    - name: CMake - Build
      run: cmake --build build --config Release --verbose
    - name: Convert ELF to Intel Extended
      run: ielftool --ihex build/Release/light-effects.elf build/Release/light-effects.hex
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: project-release
        path: |
          build/Release/light-effects.elf
          build/Release/light-effects.hex
        if-no-files-found: error

